language: python
python:
  - "2.7"
install:
  - sudo pip install -r requirements.txt --use-mirrors
script:
  - pep8 ganglr ganglr_project --exclude migrations/
  - pylint --rcfile=conf/pylint.conf ganglr --ignore migrations/